---
title: "Operating characteristics"
package: tipmap
author: "Christian Stock"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
          theme: "default"
          highlight: "default"
          toc: true
          toc_float: true
bibliography: references.bib
csl: jrss_style.csl
#bibliography: '`r system.file("references.bib", package="tipmap")`'
#csl: '`r system.file("jrss_style.csl", package="tipmap")`'
vignette: >
  %\VignetteIndexEntry{Determining a weight of the informative prior component}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options:
  chunk_output_type: console
---

```{r setup, include = F}
knitr::opts_chunk$set(
  echo = T, collapse = T, warning = F, message = F, 
  prompt = T, comment = "#", out.width = "100%"
)
```


## Introduction

Loading the `tipmap` package and `set.seed`:
```{r, eval=T, echo=T}
library(tipmap)
set.seed(123)
```


```{r data, eval=T, echo=T}
1:10
```


## Data generation


## Determining operating characteristics

...

### Probability of success

...

### Bias

...

### Coverage

...



## References



